# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-15 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_contrato', models.CharField(max_length=200)),
                ('tipo_procedimiento', models.CharField(choices=[('Licitacion Nacional', 'Licitacion Nacional'), ('Licitacion Internacional', 'Licitacion Internacional'), ('Adjudicacion Directa', 'Adjudicacion Directa'), ('Invitacion a 3 Provedores', 'Invitacion a 3 Provedores')], max_length=200)),
                ('descripcion_servicio', models.CharField(max_length=400)),
                ('provedor', models.CharField(max_length=400)),
                ('area_solicitante', models.CharField(max_length=400)),
                ('monto_contrato_siniva', models.DecimalField(decimal_places=2, max_digits=200)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=200)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('fecha_contratacion', models.DateField()),
                ('observaciones', models.CharField(max_length=400)),
                ('status', models.CharField(max_length=200)),
                ('rfc', models.CharField(max_length=200)),
                ('representante_legal', models.CharField(max_length=200)),
                ('tipo_operacion', models.CharField(choices=[('Bienes', 'Bienes'), ('Servicios', 'Servicios'), ('Obras', 'Obras')], max_length=400)),
                ('esquema_precios', models.CharField(choices=[('Fijos', 'Fijos'), ('Variables', 'Variables'), ('Unitarios', 'Unitarios'), ('Alazados', 'Alazados'), ('Mixtos', 'Mixtos')], max_length=200)),
                ('tipo_contratacion', models.CharField(choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado')], max_length=200)),
                ('plurianual', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=200)),
                ('tipo_moneda', models.CharField(max_length=200)),
                ('monto_vigente', models.DecimalField(decimal_places=2, max_digits=200)),
                ('monto_total_minima', models.DecimalField(decimal_places=2, max_digits=200)),
                ('monto_total_maximo', models.DecimalField(decimal_places=2, max_digits=200)),
                ('convenio_modificatorio', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=200)),
                ('no_convenio', models.CharField(max_length=200)),
                ('fecha_modificacion_convenio', models.DateField()),
            ],
        ),
    ]
