# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-15 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partida', models.IntegerField()),
                ('art_laassp', models.CharField(max_length=400)),
                ('no_contrato', models.CharField(max_length=400)),
                ('prov_adju', models.CharField(max_length=400)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('obje_contrato', models.CharField(max_length=400)),
                ('fir_contrato', models.DateField()),
                ('monto_contraiva', models.DecimalField(decimal_places=2, max_digits=200)),
                ('convenios', models.CharField(max_length=400)),
                ('deductivas', models.CharField(max_length=400)),
                ('dis_contrato', models.CharField(max_length=400)),
                ('total_contrato', models.DecimalField(decimal_places=2, max_digits=200)),
                ('area_respon', models.CharField(max_length=400)),
                ('for_pago', models.CharField(max_length=400)),
            ],
        ),
    ]
