from django import forms
from .models import Contrato
from django.forms import ModelForm, TextInput, DateField, NumberInput, SelectDateWidget

class ConcursoForm(forms.ModelForm):
	class Meta:
		model = Contrato
		fields = [
			'no_contrato',
			'tipo_procedimiento',
			'descripcion_servicio',
			'provedor',
			'area_solicitante',
			'monto_contrato_siniva',
			'iva',
			'monto_total',
			'fecha_inicio',
			'fecha_termino',
			'fecha_contratacion',
			'observaciones',
            'status',
            'rfc',
            'representante_legal',
            'tipo_operacion',
            'esquema_precios',
            'tipo_contratacion',
            'plurianual',
            'tipo_moneda',
            'monto_vigente',
            'monto_total_minima',
            'monto_total_maximo',
            'convenio_modificatorio',
            'no_convenio',
            'fecha_modificacion_convenio',
		]

		labels = {
			'no_contrato':'No de Contrato',
			'tipo_procedimiento':'Tipo de Procedimiento',
			'descripcion_servicio':'Descripcion de Servicio',
			'provedor':'Proveedor',
			'area_solicitante':'Area Solicitante',
			'monto_contrato_siniva':'Monto de Contrato S/IVA',
			'iva':'IVA',
			'monto_total':'Monto Total',
			'fecha_inicio':'Fecha de Inicio',
			'fecha_termino':'Fecha de Termino',
			'fecha_contratacion':'Fecha de Contratacion',
			'observaciones':'Observaciones',
            'status':'Status',
            'rfc':'RFC',
            'representante_legal':'Representante Legal',
            'tipo_operacion':'Tipo de Operaciones',
            'esquema_precios':'Esquema de Precios',
            'tipo_contratacion':'Tipo de Contratacion',
            'plurianual':'Plurianual',
            'tipo_moneda':'Tipo de Moneda',
            'monto_vigente':'Monto Vigente',
            'monto_total_minima':'Monto Total Minima',
            'monto_total_maximo':'Monto Total Maximo',
            'convenio_modificatorio':'Convenio Modificatorio',
            'no_convenio':'No de Convenio',
            'fecha_modificacion_convenio':'Fecha de Modificacion al Convenio',
		}
		widgets = {
			'no_contrato':forms.TextInput(attrs={'class':'form-control'}),
			'tipo_procedimiento':forms.Select(attrs={'class':'form-control'}),
			'descripcion_servicio':forms.Textarea(attrs={'class':'form-control'}),
			'provedor':forms.TextInput(attrs={'class':'form-control'}),
			'area_solicitante':forms.TextInput(attrs={'class':'form-control'}),
			'monto_contrato_siniva':forms.TextInput(attrs={'class':'form-control'}),
			'iva':forms.TextInput(attrs={'class':'form-control'}),
			'monto_total':forms.TextInput(attrs={'class':'form-control'}),
			'fecha_inicio':forms.SelectDateWidget(attrs={'class':'form-control'}),
			'fecha_termino':forms.SelectDateWidget(attrs={'class':'form-control'}),
			'fecha_contratacion':forms.SelectDateWidget(attrs={'class':'form-control'}),
			'observaciones':forms.TextInput(attrs={'class':'form-control'}),
            'status':forms.TextInput(attrs={'class':'form-control'}),
            'rfc':forms.TextInput(attrs={'class':'form-control'}),
            'representante_legal':forms.TextInput(attrs={'class':'form-control'}),
            'tipo_operacion':forms.Select(attrs={'class':'form-control'}),
            'esquema_precios':forms.Select(attrs={'class':'form-control'}),
            'tipo_contratacion':forms.Select(attrs={'class':'form-control'}),
            'plurianual':forms.Select(attrs={'class':'form-control'}),
            'tipo_moneda':forms.TextInput(attrs={'class':'form-control'}),
            'monto_vigente':forms.TextInput(attrs={'class':'form-control'}),
            'monto_total_minima':forms.TextInput(attrs={'class':'form-control'}),
            'monto_total_maximo':forms.TextInput(attrs={'class':'form-control'}),
            'convenio_modificatorio':forms.Select(attrs={'class':'form-control'}),
            'no_convenio':forms.TextInput(attrs={'class':'form-control'}),
            'fecha_modificacion_convenio':forms.SelectDateWidget(attrs={'class':'form-control'}),
		}
