# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-15 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contabilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_cucop', models.CharField(max_length=200)),
                ('partida', models.IntegerField()),
                ('descripcion', models.CharField(max_length=400)),
                ('unidad_medida', models.CharField(max_length=400)),
            ],
        ),
    ]
