# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-15 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogofocon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partidacatalogo', models.IntegerField()),
                ('obj_contra', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Focon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_focon', models.CharField(max_length=200)),
                ('no_oficio', models.CharField(max_length=200)),
                ('area_requirente', models.CharField(max_length=400)),
                ('descripcion', models.CharField(max_length=400)),
                ('partida', models.IntegerField()),
                ('descripcion_servicio', models.CharField(max_length=400)),
                ('monto_civa', models.DecimalField(decimal_places=2, max_digits=200)),
                ('fecha_solicitud', models.DateField()),
                ('fecha_envio', models.DateField()),
                ('entrega_requirente', models.DateField()),
                ('status', models.CharField(max_length=200)),
                ('autorizacion_babel', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Focon03',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencia', models.CharField(choices=[('Instituto Nacional de Enfermedades Respiratorias "Ismael Cosio Villegas"', 'Instituto Nacional de Enfermedades Respiratorias "Ismael Cosio Villegas"')], max_length=400)),
                ('area_requirente', models.CharField(max_length=400)),
                ('fecha_elaboracion', models.DateField()),
                ('no_requisicion', models.CharField(blank=True, max_length=400, null=True)),
                ('fecha_requerida', models.DateField()),
                ('lugar_entrega', models.CharField(choices=[('Calz Tlalpan No. 4502 Secc. XVI Bel. Dom. CP. 14080', 'Calz Tlalpan No. 4502 Secc. XVI Bel. Dom. CP. 14080')], max_length=400)),
                ('partida', models.IntegerField()),
                ('descripcion', models.CharField(max_length=400)),
                ('descripcion_detallada', models.CharField(max_length=400)),
                ('cantidad_solicitada', models.CharField(choices=[('1', '1')], max_length=400)),
                ('unidad_medida', models.CharField(choices=[('Servicio', 'Servicio')], max_length=400)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=200)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=200)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=200)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=200)),
                ('otros_gravamenes', models.DecimalField(blank=True, decimal_places=2, max_digits=200, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=200)),
                ('anexos', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=400)),
                ('anticipo', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=400)),
                ('autorizacion_presupuesto', models.CharField(max_length=400)),
                ('existencia_almacen', models.CharField(choices=[('N/A', 'N/A')], max_length=400)),
                ('observaciones', models.CharField(max_length=400)),
                ('registro_sanitario', models.CharField(max_length=400)),
                ('normas', models.CharField(max_length=400)),
                ('capacitacion', models.CharField(max_length=400)),
                ('pais_origen', models.CharField(choices=[('Nacional (Mexico)', 'Nacional (Mexico)')], max_length=400)),
                ('metodo_prueba', models.CharField(max_length=400)),
                ('tipo_garantia1', models.CharField(choices=[('N/A', 'N/A'), ('Anticipo', 'Anticipo'), ('Cumplimiento divisible', 'Cumplimiento divisible'), ('Cumplimiento indivisible', 'Cumplimiento indivisible'), ('Vicios ocultos', 'Vicios ocultos'), ('Defectos o Calidad/Poliza de responsbilidad civil/otra', 'Defectos o Calidad/Poliza de responsbilidad civil/otra')], max_length=400)),
                ('tipo_garantia2', models.CharField(choices=[('N/A', 'N/A'), ('Anticipo', 'Anticipo'), ('Cumplimiento divisible', 'Cumplimiento divisible'), ('Cumplimiento indivisible', 'Cumplimiento indivisible'), ('Vicios ocultos', 'Vicios ocultos'), ('Defectos o Calidad/Poliza de responsbilidad civil/otra', 'Defectos o Calidad/Poliza de responsbilidad civil/otra')], max_length=400)),
                ('tipo_garantia3', models.CharField(choices=[('N/A', 'N/A'), ('Anticipo', 'Anticipo'), ('Cumplimiento divisible', 'Cumplimiento divisible'), ('Cumplimiento indivisible', 'Cumplimiento indivisible'), ('Vicios ocultos', 'Vicios ocultos'), ('Defectos o Calidad/Poliza de responsbilidad civil/otra', 'Defectos o Calidad/Poliza de responsbilidad civil/otra')], max_length=400)),
                ('porcentaje1', models.CharField(max_length=400)),
                ('porcentaje2', models.CharField(max_length=400)),
                ('porcentaje3', models.CharField(max_length=400)),
                ('plurianualidad', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=400)),
                ('meses', models.CharField(max_length=400)),
                ('penas_convencionales', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=400)),
                ('porcentaje_penas', models.CharField(max_length=400)),
                ('tiempo_fabricacion', models.CharField(choices=[('N/A', 'N/A')], max_length=400)),
                ('condiciones_entrega', models.CharField(max_length=400)),
                ('solicita', models.CharField(max_length=400)),
                ('autoriza', models.CharField(max_length=400)),
                ('clave_cucop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Contabilidad')),
            ],
        ),
    ]
