from django import forms
from .models import Focon, Focon03
from django.forms import ModelForm, TextInput, DateField, NumberInput, SelectDateWidget, Textarea

class FoconForm(forms.ModelForm):
	class Meta:
		model = Focon
		fields = [
			'no_focon',
			'no_oficio',
			'area_requirente',
			'descripcion',
			'partida',
			'descripcion_servicio',
			'monto_civa',
			'fecha_solicitud',
			'fecha_envio',
			'entrega_requirente',
			'status',
			'autorizacion_babel',
		]

		labels = {
			'no_focon':'No de Focon',
			'no_oficio':'No de Oficio',
			'area_requirente':'Area Requirente',
			'descripcion':'Descripcion',
			'partida':'Partida',
			'descripcion_servicio':'Descripcion del Servicio',
			'monto_civa':'Monto C/iva',
			'fecha_solicitud':'Fecha de Solicitud',
			'fecha_envio':'Fecha de Envio',
			'entrega_requirente':'Entrega Requirente',
			'status':'Status',
			'autorizacion_babel':'Autorizacion Babel',
		}
		widgets = {
			'no_focon':forms.TextInput(attrs={'class':'form-control'}),
			'no_oficio':forms.TextInput(attrs={'class':'form-control'}),
			'area_requirente':forms.TextInput(attrs={'class':'form-control'}),
			'descripcion':forms.TextInput(attrs={'class':'form-control'}),
			'partida':forms.TextInput(attrs={'class':'form-control'}),
			'descripcion_servicio':forms.TextInput(attrs={'class':'form-control'}),
			'monto_civa':forms.TextInput(attrs={'class':'form-control'}),
			'fecha_solicitud':forms.SelectDateWidget(attrs={'class':'form-control'}),
			'fecha_envio':forms.SelectDateWidget(attrs={'class':'form-control'}),
			'entrega_requirente':forms.TextInput(attrs={'class':'form-control'}),
			'status':forms.TextInput(attrs={'class':'form-control'}),
			'autorizacion_babel':forms.TextInput(attrs={'class':'form-control'}),
		}

class Focon03Form(forms.ModelForm):
	class Meta:
		model = Focon03
		fields = [
			'dependencia',
			'area_requirente',
			'fecha_elaboracion',
			'no_requisicion',
			'fecha_requerida',
			'lugar_entrega',
			'clave_cucop',
			'partida',
			'descripcion',
			'descripcion_detallada',
			'cantidad_solicitada',
			'unidad_medida',
			'precio_unitario',
			'importe',
			'subtotal',
			'iva',
			'otros_gravamenes',
			'total',
			'anexos',
			'anticipo',
			'autorizacion_presupuesto',
			'existencia_almacen',
			'observaciones',
			'registro_sanitario',
			'normas',
			'capacitacion',
			'pais_origen',
			'metodo_prueba',
			'tipo_garantia1',
			'tipo_garantia2',
			'tipo_garantia3',
			'porcentaje1',
			'porcentaje2',
			'porcentaje3',
			'plurianualidad',
			'meses',
			'penas_convencionales',
			'porcentaje_penas',
			'tiempo_fabricacion',
			'condiciones_entrega',
			'solicita',
			'autoriza',
		]
		labels = {
			'dependencia': 'Dependencia',
			'area_requirente' : 'Area Requirente',
			'fecha_elaboracion' : 'Fecha de Elaboracion',
			'no_requisicion' : 'No de Requisicion',
			'fecha_requerida' : 'Fecha Requerida',
			'lugar_entrega' : 'Lugar de Entrega',
			'clave_cucop' : 'Clave CUCOP',
			'partida' : 'Partida',
			'descripcion' : 'Descripcion',
			'descripcion_detallada' : 'Descripcion Detallada',
			'cantidad_solicitada' : 'Cantidad Solicitada',
			'unidad_medida' : 'Unidad de Medida',
			'precio_unitario' : 'Precio Unitario',
			'importe' : 'Importe',
			'subtotal' : 'Subtotal',
			'iva' : 'IVA',
			'otros_gravamenes' : 'Otros Gravamenes',
			'total' : 'Total',
			'anexos' : 'Anexos',
			'anticipo' : 'Anticipo',
			'autorizacion_presupuesto' : 'Autorizacion del Presupuesto',
			'existencia_almacen' : 'Existencia de Alamacen',
			'observaciones' : 'Observaciones',
			'registro_sanitario' : 'Registro Sanitario',
			'normas' : 'Normas',
			'capacitacion' : 'Capacitacion',
			'pais_origen' : 'Pais de Origen',
			'metodo_prueba' : 'Metodo de Prueba',
			'tipo_garantia1' : 'Tipo de Garantia 1',
			'tipo_garantia2' : 'Tipo de Garantia 2',
			'tipo_garantia3' : 'Tipo de Garantia 3',
			'porcentaje1' : 'Porcentaje 1',
			'porcentaje2' : 'Porcentaje 2',
			'porcentaje3' : 'Porcentaje 3',
			'plurianualidad' : 'Plurianualidad',
			'meses' : 'Meses',
			'penas_convencionales' : 'Penas Convencionales',
			'porcentaje_penas' : 'Porcentaje de Penas',
			'tiempo_fabricacion' : 'Tiempo de Fabricacion',
			'condiciones_entrega' : 'Condiciones de Entrega',
			'solicita' : 'Anotar nombre, cargo y firma del titular del araea solicitante',
			'autoriza' : 'Anotar nombre, cargo y firma del titular del servicor publico que autoriza',

		}
		widgets = {
			'dependencia': forms.Select(attrs={'class':'form-control'}),
			'area_requirente': forms.TextInput(attrs={'class':'form-control'}),
			'fecha_elaboracion': forms.SelectDateWidget(attrs={'class':'form-control'}),
			'no_requisicion': forms.TextInput(attrs={'class':'form-control'}),
			'fecha_requerida': forms.SelectDateWidget(attrs={'class':'form-control'}),
			'lugar_entrega': forms.Select(attrs={'class':'form-control'}),
			'clave_cucop': forms.Select(attrs={'class':'form-control'}),
			'partida': forms.TextInput(attrs={'class':'form-control'}),
			'descripcion': forms.Textarea(attrs={'class':'form-control'}),
			'descripcion_detallada' :forms.Textarea(attrs={'class':'form-control'}),
			'cantidad_solicitada': forms.Select(attrs={'class':'form-control'}),
			'unidad_medida': forms.Select(attrs={'class':'form-control'}),
			'precio_unitario': forms.TextInput(attrs={'class':'form-control'}),
			'importe': forms.TextInput(attrs={'class':'form-control'}),
			'subtotal': forms.TextInput(attrs={'class':'form-control'}),
			'iva': forms.TextInput(attrs={'class':'form-control'}),
			'otros_gravamenes': forms.TextInput(attrs={'class':'form-control'}),
			'total': forms.TextInput(attrs={'class':'form-control'}),
			'anexos': forms.Select(attrs={'class':'form-control'}),
			'anticipo': forms.Select(attrs={'class':'form-control'}),
			'autorizacion_presupuesto': forms.TextInput(attrs={'class':'form-control'}),
			'existencia_almacen': forms.Select(attrs={'class':'form-control'}),
			'observaciones': forms.TextInput(attrs={'class':'form-control'}),
			'registro_sanitario': forms.TextInput(attrs={'class':'form-control'}),
			'normas': forms.TextInput(attrs={'class':'form-control'}),
			'capacitacion': forms.TextInput(attrs={'class':'form-control'}),
			'pais_origen': forms.Select(attrs={'class':'form-control'}),
			'metodo_prueba': forms.TextInput(attrs={'class':'form-control'}),
			'tipo_garantia1': forms.Select(attrs={'class':'form-control'}),
			'tipo_garantia2': forms.Select(attrs={'class':'form-control'}),
			'tipo_garantia3': forms.Select(attrs={'class':'form-control'}),
			'porcentaje1': forms.TextInput(attrs={'class':'form-control'}),
			'porcentaje2': forms.TextInput(attrs={'class':'form-control'}),
			'porcentaje3': forms.TextInput(attrs={'class':'form-control'}),
			'plurianualidad': forms.Select(attrs={'class':'form-control'}),
			'meses': forms.TextInput(attrs={'class':'form-control'}),
			'penas_convencionales': forms.Select(attrs={'class':'form-control'}),
			'porcentaje_penas': forms.TextInput(attrs={'class':'form-control'}),
			'tiempo_fabricacion': forms.Select(attrs={'class':'form-control'}),
			'condiciones_entrega': forms.TextInput(attrs={'class':'form-control'}),
			'solicita': forms.Textarea(attrs={'class':'form-control'}),
			'autoriza': forms.Textarea(attrs={'class':'form-control'}),
		}
